### ISSUE TITLE
Every request returns not submitable and getIssues() only returns [{"message":"Request invalid."}]

### ISSUE THREAD

**Issue by MaPhiKo** [mosparo/php-api-client#1]
After successfully using the frontend part of Mosparo, I've been trying to get the backend part to work via this client.
Unfortunately I only get false from $result->isSubmittable() and when I try to use getIssues() to debug it returns [{"message":"Request invalid."}].
I can't seem to find the error getIssues() returns in the code.

I checked the server log but the response is always code 200.
Example:
[20/Nov/2023:12:04:17 +0100] "POST /api/v1/verification/verify HTTP/1.1" 200 48 "-" "GuzzleHttp/7"

My minimal implementation I tried it with after it didn't work in my project looks as follow:
(I removed my project data for the screenshot)
index.php
![grafik](https://github.com/mosparo/php-api-client/assets/76614551/5fd1d23b-d1bf-409e-bc4c-2344ac23ae6e)

mail.php
![grafik](https://github.com/mosparo/php-api-client/assets/76614551/2b75e543-bcbd-482a-83ed-9d77d8231339)

As stated before the frontend part works as intended.

**Comment by zepich** [comment]
Hi @MaPhiKo 

Thank you very much for your issue.

The error means that mosparo could not authenticate the request. Since you're using the PHP API client, there are only a few options for what the issue could be.

The main reason could be that the public or private key is wrong. Are these two correct and from the correct project? The public key is valid (otherwise, there would be a different error message), but maybe from another project? 

Kind regards,

zepich

**Comment by MaPhiKo** [comment]
Thank you for the very timely response. 
I am embarrassed to say it was an issue with the private key. 

Are the possible error messages listed somewhere in the documentation and I missed them? "Request invalid." wasn't clear to me.

**Comment by zepich** [comment]
Thank you very much for your response. I'm happy that it was a simple issue.

> Are the possible error messages listed somewhere in the documentation and I missed them? "Request invalid." wasn't clear to me.

No, not right now. But that's a good idea. I will add them to the documentation with possible reasons for the error (like, in your case, the wrong private key).

With the next (minor) mosparo version, v1.1, we've added an API debug mode, which will show you more information in case of an error. It will show you that the received authentication signature is different from the expected one, which means that something in creating the signature is not good (either the payload is not the same or the private key is wrong).
